### PR TITLE
gcr.io/google-containers -> k8s.gcr.io

### PR DESCRIPTION
**Pull request by dekkagaijin**
Use the real repo, rather than rely on one of GCR's docker bug mitigations

### CODE REVIEW

**Comment by dekkagaijin** [comment]
@kashomon ptal

**Comment by ixdy** [comment]
why not just use the alias `k8s.gcr.io`?

**Comment by dekkagaijin** [comment]
@ixdy that'd be fine, too

**Comment by Kashomon** [comment]
LGTM

**Pull request merged**
